supercontest/models/__init__.py
from .models import User, Season, Week, Line, Pick, Score

client/supercontest/__init__.py
import requests
import bs4

def query(email, password, query):
    """Runs a single query in a single session to fetch supercontest data
    programatically. It first uses your credentials to retrieve a valid
    CSRF token, then runs the query against the graphql endpoint.

    Args:
        email (str): Your email credential
        password (str): Your password credential (this is passed
            encrypted over https)
        query (str): The graphql query string to run

    Returns:
        (json) The data your query returned
    """
    creds = dict(email=email, password=password)
    root_url = 'https://southbaysupercontest.com'

    with requests.session() as session:
        response = session.get(root_url)
        soup = bs4.BeautifulSoup(response.text, 'html.parser')
        csrf_token = soup.find(id='csrf_token')['value']
        creds['csrf_token'] = csrf_token
        session.post(root_url + '/user/sign-in',
                     data=creds,
                     headers=dict(referer=response.url))
        response = session.get(root_url + '/graphql',
                               json=dict(query=query))
    data = response.json()

    return data

supercontest/__init__.py
# pylint: disable=cyclic-import
# This toplevel package imports some modules to build the app.
# but it's protected by the get_app function, which is not called here
# but my the modules themselves.
import os
from flask import Flask
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
import flask_monitoringdashboard as dashboard
from flask_migrate import Migrate
from flask_mail import Mail
from flask_user import UserManager, login_required
from flask_wtf.csrf import CSRFProtect
from flask_graphql import GraphQLView
from wtforms.fields import HiddenField

# pylint: disable=invalid-name
db = SQLAlchemy()
migrate = Migrate()
mail = Mail()
csrf_protect = CSRFProtect()
toolbar = DebugToolbarExtension()
# pylint: enable=invalid-name


def is_hidden_field_filter(field):
    return isinstance(field, HiddenField)


def get_headerless_conf(pth):
    with open(pth) as filehandle:
        content = filehandle.readlines()
    return {line.split('=')[0]:line.split('=')[1].strip() for line in content
            if not line.startswith('#')}


def get_app(db_name=None, db_port=None, db_host=None, extra_config_settings={}):  # pylint: disable=dangerous-default-value,too-many-locals
    """You may pass the name/port/host of the db if you want to deviate
    from the standard configs (staging/production). This is used for testing.
    extra_config_settings is forwarded to app.config during instantiation of Flask.
    """
    curdir = os.path.dirname(os.path.abspath(__file__))

    dev_mode = bool(os.environ.get('SC_DEV'))

    app = Flask(__name__)
    app.config.from_pyfile(os.path.join(curdir, 'config', 'public.py'))
    app.config.from_pyfile(os.path.join(curdir, 'config', 'private.py'))
    app.config.update(extra_config_settings)
    app.config['DEBUG'] = dev_mode

    # The flask app reads the database configs directly, rather than being passed them
    # through the env in docker. This means runserver and other debug/dev methods
    # aren't FULLY coupled to docker-compose. Runserver still won't work because it now expects
    # the db in another container on a certain port, but you can still use it for
    # light smoketesting.
    db_conf_dir = os.path.join(curdir, '..', 'docker', 'database')
    db_public_conf = get_headerless_conf(os.path.join(db_conf_dir, 'public.conf'))
    db_private_conf = get_headerless_conf(os.path.join(db_conf_dir, 'private.conf'))
    db_conf = {**db_public_conf, **db_private_conf}
    app.config['SQLALCHEMY_DATABASE_URI'] = \
        'postgresql://{user}:{password}@{host}:{port}/{database}'.format(
            user=db_conf['POSTGRES_USER'],
            password=db_conf['POSTGRES_PASSWORD'],
            host=db_host or db_conf['POSTGRES_HOST'],
            port=db_port or db_conf['POSTGRES_PORT'],
            database=db_name or db_conf['POSTGRES_DB'])

    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    csrf_protect.init_app(app)

    from supercontest.views import register_blueprints  # pylint: disable=wrong-import-position
    register_blueprints(app)

    from supercontest.models import User  # pylint: disable=wrong-import-position
    user_manager = UserManager(app, db, User)

    app.jinja_env.globals['bootstrap_is_hidden_field'] = is_hidden_field_filter  # pylint: disable=no-member

    # Make the function for displaying dates available to the templates
    from supercontest.core.utilities import convert_date
    app.jinja_env.globals['convert_date'] = convert_date  # pylint: disable=no-member

    @app.context_processor
    def context_processor():  # pylint: disable=unused-variable
        return dict(user_manager=user_manager)

    # Add graphql view.
    from supercontest.graphql import schema
    # Intentionally allowing users in production to use graphiql to explore
    # the db because it still requires auth. To disable this in dev mode,
    # set graphiql=dev_mode instead of True.
    view = GraphQLView.as_view('graphql', schema=schema, graphiql=True)
    app.add_url_rule('/graphql', view_func=login_required(csrf_protect.exempt(view)))

    # Add the dashboard.
    this_dir = os.path.dirname(os.path.realpath(__file__))
    fmd_cfg = os.path.join(this_dir, 'config', 'dashboard.cfg')
    dashboard.config.init_from(file=fmd_cfg)
    dashboard.bind(app)
    csrf_protect.exempt(dashboard.blueprint)

    # Add the debug toolbar.
    toolbar.init_app(app)

    return app

supercontest/commands/__init__.py
from .commands import (
    CommitLinesCommand,
    CommitScoresCommand,
)

supercontest/dbsession/__init__.py
"""Wrappers around all interactions with the db.session: mostly
queries and commits.

The modules in this package are the only ones in the entire
distribution that should invoke the db object.

This makes the application side of migrations much easier to update.
"""

supercontest/graphql/__init__.py
from .schema import schema

supercontest/views.py
from flask import render_template, redirect, url_for
from flask_login import login_required, current_user

from supercontest import app
from supercontest.forms import EmailPasswordForm


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/login', methods=['GET', 'POST'])
def login():
    form = EmailPasswordForm()
    # if form.validate_on_submit():
    #    # check password here later
    #    return redirect(url_for('index'))
    return render_template('login.html', form=form)


# @APP.route('/')
# def home():
#     week, results = compare_scores_to_lines()
#     trs_list = []
#     for result in results:
#         status = result.pop(-1)
#         tds_list = ['<td>{}</td>'.format(cell) for cell in result]
#         if status == 'game is over':
#             if float(result[-1]) > float(result[-2]):
#                 tds_list[0] = tds_list[0].replace('td', 'td bgcolor=lightgreen', 1)
#             elif float(result[-2]) == float(result[-1]):
#                 tds_list[0] = tds_list[0].replace('td', 'td bgcolor=lightblue', 1)
#                 tds_list[1] = tds_list[1].replace('td', 'td bgcolor=lightblue', 1)
#             else:
#                 tds_list[1] = tds_list[1].replace('td', 'td bgcolor=lightgreen', 1)
#         tds_str = ''.join(tds_list)
#         trs_list.append('<tr>{}</tr>'.format(tds_str))
#     trs_str = ''.join(trs_list)
# 
#     return render_template('home.html', week=week, trs=trs_str)

supercontest/views/__init__.py
from .views import season_week_blueprint, main_blueprint


def register_blueprints(app):
    app.register_blueprint(season_week_blueprint)
    app.register_blueprint(main_blueprint)

supercontest/views/views.py
import json
from itertools import accumulate
from flask import Blueprint, render_template, request, redirect, url_for, Response, g
from flask_user import current_user, login_required
import plotly

from supercontest.dbsession import queries
from supercontest.core.picks import PICK_DAYS, commit_picks, InvalidPicks
from supercontest.core.scores import commit_scores
from supercontest.core.utilities import is_today, get_team_abv_map
from supercontest.core.results import (
    RESULTS_DAYS,
    determine_current_pick_points,
    determine_current_coverer,
    get_week_teams,
    get_sorted_week_teams,
    get_all_week_totals,
    get_season_totals,
)

# This is the primary blueprint of the application. If flask supported nested
# blueprints, I'd do one for season and one for week, but they're both here.
# Many routes in the supercontest are data-specific to the season and week.
season_week_blueprint = Blueprint('season_week',  # pylint: disable=invalid-name
                                  __name__,
                                  template_folder='templates',
                                  static_folder='static')
only_season_endpoints = ['season_week.leaderboard', 'season_week.graph']  # pylint: disable=invalid-name


@season_week_blueprint.url_defaults
def define_week(endpoint, values):  # pylint: disable=unused-argument
    """If the user goes to the website's home / without any week or season
    specification, query the database for the most recent matchups and go
    to that page.
    """
    if not values.get('season'):
        values['season'] = queries.get_max_season()
    if not values.get('week') and endpoint not in only_season_endpoints:
        values['week'] = queries.get_max_week(season=values['season'])


@season_week_blueprint.url_value_preprocessor
def get_week(endpoint, values):  # pylint: disable=unused-argument
    """Attributes current and available weeks and seasons to the g object for
    use in subsequent routes. url_defaults obviously executes before this.

    This also adds the useful is_current_week, which is a logical condition for
    many other actions.
    """
    g.available_seasons = queries.get_sorted_seasons()
    g.season = int(values.pop('season'))
    g.is_current_season = g.season == max(g.available_seasons)
    if endpoint not in only_season_endpoints:
        g.available_weeks = queries.get_sorted_weeks(season=g.season)
        g.week = int(values.pop('week'))
        g.is_current_week = g.is_current_season and g.week == max(g.available_weeks)


@season_week_blueprint.route('/season<season>/week<week>/matchups')
@login_required
def matchups():
    if g.is_current_week and is_today(RESULTS_DAYS):
        commit_scores(season=g.season, week=g.week)
    sorted_matchups = queries.get_sorted_matchups(season=g.season, week=g.week)
    # Get the picks to overlay. We only need the team names.
    pick_teams = [row.team for row in queries.get_picks(season=g.season,
                                                        week=g.week,
                                                        user_id=current_user.id)]
    if g.is_current_week and is_today(PICK_DAYS):
        msg = ('Make your picks by clicking on the teams below, '
               'then click submit at the bottom.')
    else:
        msg = ''
    # Since we already need team names to highlight picks, determine which
    # teams are covering in order to colorize.
    cover_status = {matchup.line_id: determine_current_coverer(matchup)
                    for matchup in sorted_matchups}
    return render_template('matchups.html',
                           sorted_matchups=sorted_matchups,
                           pick_teams=pick_teams,
                           cover_status=cover_status,
                           message=msg)


@season_week_blueprint.route('/season<season>/week<week>/picks')
@login_required
def picks():
    if g.is_current_week and is_today(RESULTS_DAYS):
        commit_scores(season=g.season, week=g.week)
    sorted_matchups = queries.get_sorted_matchups(season=g.season, week=g.week)
    # The matchups will be the column headers in the frontend table. We now need
    # the rows (user IDs) mapped with picked teams. If picks aren't locked down
    # yet, you're only going to report the info for the active user.
    if g.is_current_week and is_today(PICK_DAYS):
        _picks = get_week_teams(season=g.season, week=g.week, user_id=current_user.id)
        msg = ('To make or modify your picks, go to the <a href={}>{}</a> tab.<br>'
               'You may do this as much as you want until lockdown on Saturday night '
               'at midnight.<br>Everyone\'s picks will publish here at that time.'.format(
                   url_for('season_week.matchups'), 'Matchups'))
    else:
        _picks = get_week_teams(season=g.season, week=g.week)
        msg = ''
    # Now we need the status and current points in order to sort and display the
    # picks properly.
    status_map = {}
    points_map = {}
    for _matchup in sorted_matchups:
        status_map[_matchup.favored_team] = _matchup.status
        status_map[_matchup.underdog_team] = _matchup.status
        points_map[_matchup.favored_team] = determine_current_pick_points(
            row=_matchup, team=_matchup.favored_team)
        points_map[_matchup.underdog_team] = determine_current_pick_points(
            row=_matchup, team=_matchup.underdog_team)
    # And then order the users by total week score for the picks view.
    sorted_picks = get_sorted_week_teams(_picks, points_map)
    # And lastly we want to display slightly different data than the raw.
    id_name_map = queries.get_id_name_map()
    team_abv_map = get_team_abv_map()
    return render_template('picks.html',
                           sorted_matchups=sorted_matchups,
                           sorted_picks=sorted_picks,
                           id_name_map=id_name_map,  # used in template
                           team_abv_map=team_abv_map,  # used in template
                           points_map=json.dumps(points_map),  # dumped for js use
                           status_map=json.dumps(status_map),  # dumped for js use
                           message=msg)


@season_week_blueprint.route('/season<season>/leaderboard')
@login_required
def leaderboard():
    # If the lb or graph is being requested for the most recent season,
    # then fetch/calc/commit results for the most recent week of that season.
    # Only color the completed weeks.
    max_week = queries.get_max_week(season=g.season)
    if g.is_current_season and is_today(RESULTS_DAYS):
        commit_scores(season=g.season, week=max_week)
        color_week = max_week - 1
    else:
        color_week = max_week
    all_week_totals = get_all_week_totals(season=g.season)  # unsorted
    season_totals = get_season_totals(all_week_totals=all_week_totals)  # sorted
    id_name_map = queries.get_id_name_map()
    id_email_map = queries.get_id_email_map()
    max_points = color_week*5  # for total percentage display
    return render_template('leaderboard.html',
                           all_week_totals=all_week_totals,
                           season_totals=season_totals,
                           color_week=color_week,
                           id_name_map=id_name_map,
                           id_email_map=id_email_map,
                           max_points=max_points)


@season_week_blueprint.route('/season<season>/graph')
@login_required
def graph():
    # If the lb or graph is being requested for the most recent season,
    # then fetch/calc/commit results for the most recent week of that season.
    # Only graph the completed weeks.
    max_week = queries.get_max_week(season=g.season)
    if g.is_current_season and is_today(RESULTS_DAYS):
        commit_scores(season=g.season, week=max_week)
        graph_week = max_week - 1
    else:
        graph_week = max_week
    all_week_totals = get_all_week_totals(season=g.season)  # unsorted
    season_totals = get_season_totals(all_week_totals=all_week_totals)  # sorted
    id_name_map = queries.get_id_name_map()
    # Iterate over the sorted season totals so the graph legend shows names
    # in the same order as the leaderboard. If we didn't care about the sorting,
    # we'd just need all_week_totals to accumulate.
    data = []
    for user_id, _ in season_totals:
        weekly_data = all_week_totals[user_id]
        sorted_weeks = list(sorted([week for week in weekly_data.keys()
                                    if week <= graph_week]))
        sorted_points = [weekly_data[week] for week in sorted_weeks]
        is_current_user = user_id == current_user.id
        _graph = plotly.graph_objs.Scatter(
            # Note that a zero week with zero points is prepended to both arrays
            # to make the visualization better around the origin.
            x=[0]+sorted_weeks,
            y=list(accumulate([0]+sorted_points)),
            name=id_name_map[user_id],
            visible=(True if is_current_user else 'legendonly')
        )
        data.append(_graph)
    data_json = json.dumps(data, cls=plotly.utils.PlotlyJSONEncoder)
    # Layout (titles, axes, etc) is handled in JS.
    return render_template('graph.html', dataJSON=data_json)


# The "main" blueprint is the collection of all other views, the ones that
# don't require a season or week to be specified.
main_blueprint = Blueprint('main',  # pylint: disable=invalid-name
                           __name__,
                           template_folder='templates',
                           static_folder='static')


@main_blueprint.route('/')
@login_required
def home():
    return redirect(url_for('season_week.matchups'))


@main_blueprint.route('/feedback')
@login_required
def feedback():
    return render_template('feedback.html')


@main_blueprint.route('/rules')
@login_required
def rules():
    return render_template('rules.html')


@main_blueprint.route('/pick', methods=['POST'])
@login_required

supercontest/templates/adspace.html
{% extends "layout.html" %}

{% block layout_content %}

<div class="jumbotron jumbotron-fluid mb-0" style="height: 150px; background: url({{ url_for('static', filename='img/warriors.svg') }}); background-size: contain; background-repeat: repeat-x;">
</div>

<div class="container-fluid mt-3">
    <div class="row justify-content-center">
        <div class="col">
            {% block adspace_content %}
            {% endblock %}
        </div>
    </div>
</div>

{% endblock %}

supercontest/templates/feedback.html
{% extends "settings_navs.html" %}

{% block settings_navs_content %}

<div class="row justify-content-center mt-3">
    <div class="col-sm-10 col-lg-6">
        <h3>Your input is wanted!</h3>
        <form action="/">
            <div class="form-group">
                <label for="myTextBox">How can we make the app better?</label>
                <input type="text" class="form-control" id="myTextBox" autofocus="autofocus">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<script src="{{ url_for('static', filename='js/feedback.js') }}"></script>

{% endblock %}

supercontest/templates/flask_user_layout.html
{% extends "settings_navs.html" %}

{% block settings_navs_content %}

{% block extra_css %}
{% endblock %}

{% block body %}

<div class="row justify-content-center my-3">
    <div class="col-sm-5 col-md-4 col-lg-3">
        <div id="main-div">
            {% block main %}
                {% block content %}
                {% endblock %}
            {% endblock %}
        </div>
    </div>
</div>

{% block flash_messages %}
    {%- with messages = get_flashed_messages(with_categories=true) -%}
        {% if messages %}
            {% for category, message in messages %}
                {% if category=='error' %}
                    {% set category='danger' %}
                {% endif %}
                <div class="alert alert-{{category}}">{{ message|safe }}</div>
            {% endfor %}
        {% endif %}
    {%- endwith %}
{% endblock %}

{% endblock %}

{% block extra_js %}
{% endblock %}

{% endblock %}

supercontest/templates/graph.html
{% extends "main_navs.html" %}

{% block main_navs_content %}

<div class="row justify-content-center">
    <div id="scoreGraph" class="col"></div>
</div>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script>const data = {{ dataJSON | safe }};</script>
<script src="{{ url_for('static', filename='js/graph.js') }}"></script>

{% endblock %}

supercontest/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% if csrf_token is defined %}
        <meta name="csrf-token" content="{{ csrf_token() }}">
        {% endif %}
        <title>{{ user_manager.USER_APP_NAME }}</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    </head>
    <body>
        {% block layout_content %}
        {% endblock %}
        <script src="{{ url_for('static', filename='js/nav_active.js') }}"></script>
    </body>
</html>

supercontest/templates/leaderboard.html
{% extends "main_navs.html" %}

{% block main_navs_content %}

<div class="row justify-content-center mt-3">
    <div class="col-sm-12 col-lg-10">
        <div class="table-responsive"> 
            <table class="table table-sm table-bordered table-striped table-hover text-center">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Rank</th>
                        <th scope="col">User</th>
                        {% for week in range(1, 18) %}
                        <th scope="col">{{ week }}</th>
                        {% endfor %}
                        <th scope="col">Total</th>
                        <th scope="col">%</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user_id, total_points in season_totals %}
                    {% if user_id == current_user.id %}
                    <tr style="border: 2px solid;">
                    {% else %}
                    <tr>
                    {% endif %}
                        <th scope="row">{{ loop.index }}</td>
                        <td data-toggle="tooltip" title="{{ id_email_map[user_id] }}">
                            {{ id_name_map[user_id] }}
                        </td>
                        {% for week in range(1, 18) %}
                        <td class="weekScore">{{ all_week_totals[user_id].get(week, 0.0) }}</td>
                        {% endfor %}
                        <th scope="row">{{ total_points }}</td>
            			{% set percent = total_points / max_points * 100 %}
                        <th scope="row">{{ '%0.1f' % percent }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>const colorWeek = {{ color_week }}</script>
<script src="{{ url_for('static', filename='js/leaderboard.js') }}"></script>

{% endblock %}

supercontest/templates/main_navs.html
{% extends "season_navs.html" %}

{% block season_navs_content %}

<div class="row justify-content-center mt-2">
    <ul class="nav nav-tabs">
        <div class="col text-center"><li class="nav-item">
            <a id="nav_matchups" class="nav-link" href="{{ url_for('season_week.matchups', season=g.season, week=g.week) }}">
                Matchups
            </a>
        </li></div>
        <div class="col text-center"><li class="nav-item">
            <a id="nav_picks" class="nav-link" href="{{ url_for('season_week.picks', season=g.season, week=g.week) }}">
                Picks
            </a>
        </li></div>
        <div class="col text-center"><li class="nav-item">
            <a id="nav_leaderboard" class="nav-link" href="{{ url_for('season_week.leaderboard', season=g.season) }}">
                Leaderboard
            </a>
        </li></div>
        <div class="col text-center"><li class="nav-item">
            <a id="nav_graph" class="nav-link" href="{{ url_for('season_week.graph', season=g.season) }}">
                Graph
            </a>
        </li></div>
    </ul>
</div>

{% block main_navs_content %}
{% endblock %}

{% endblock %}

supercontest/templates/picks.html
{% extends "week_navs.html" %}

{% block week_navs_content %}

{% if message %}
<p class="text-center mt-3">{{ message|safe }}</p>
{% endif %}

<div class="row justify-content-center mt-3">
    <div class="col-lg-11">
        <div class="table-responsive" id="tableDiv">
            <table class="table table-sm table-bordered table-striped table-hover text-center">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">User</th>
                        {% for matchup in sorted_matchups %}
                        <th scope="col">{{ team_abv_map[matchup.favored_team] }}</th>
                        <th scope="col">{{ team_abv_map[matchup.underdog_team] }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for data in sorted_picks %}
                    {% if data[0] == current_user.id and sorted_picks|length > 1 %}
                    <tr style="border: 2px solid;">
                    {% else %}
                    <tr>
                    {% endif %}
                        <td>{{ id_name_map[data[0]] }}</td>
                        {% for matchup in sorted_matchups %}
                        <td id={{ data[0]|string + matchup.favored_team }} style="color: rgb(225, 225, 225)" data-toggle="tooltip" title="+{{ matchup.line }}">
                            {{ team_abv_map[matchup.favored_team] }}
                        </td>
                        <td id={{ data[0]|string + matchup.underdog_team }} style="color: rgb(225, 225, 225)" data-toggle="tooltip" title="-{{ matchup.line }}">
                            {{ team_abv_map[matchup.underdog_team] }}
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>const sorted_picks = {{ sorted_picks|tojson }}</script>
<script>const statusMap = {{ status_map|safe }}</script>
<script>const pointsMap = {{ points_map|safe }}</script>
<script src="{{ url_for('static', filename='js/picks.js') }}"></script>

{% endblock %}

supercontest/templates/results.html
<html>
  <head>
    <title>South Bay Supercontest</title>
  </head>
  <body>
    <div class="container">
      <h2>South Bay Supercontest Results: Week {{ week }}</h2>
      <table border=black cellpadding=5>
        <tr>
          <th>Favored</th>
          <th>Underdog</th>
          <th>Datetime</th>
          <th>Line</th>
          <th>Score Delta</th>
        </tr>
        {{ trs|safe }}
      </table>
    </div>
  </body>
</html>

supercontest/templates/rules.html
{% extends "settings_navs.html" %}

{% block settings_navs_content %}

<script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2/webcomponents-loader.min.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@1/src/zero-md.min.js"></script>

<div class="row justify-content-center my-3">
    <div class="col-sm-10 col-md-8 col-lg-6">
        <zero-md src="{{ url_for('static', filename='RULES.md') }}"></zero-md>
    </div>
</div>

{% endblock %}

supercontest/templates/season_navs.html
{% extends "settings_navs.html" %}

{% block settings_navs_content %}

<div class="row justify-content-center mt-2">
    <ul class="nav nav-tabs">
        {% for season in g.available_seasons %}
            <div class="col text-center"><li class="nav-item">
                <a id="nav_season{{ season }}" class="nav-link" href="{{ url_for(request.url_rule.endpoint, season=season) }}">{{ season }}</a>
            </li></div>
        {% endfor %}
    </ul>
</div>

{% block season_navs_content %}
{% endblock %}

<script>
    const season = {{ g.season }};
    const available_seasons = {{ g.available_seasons }};
</script>

{% endblock %}

supercontest/templates/settings_navs.html
{% extends "adspace.html" %}

{% block adspace_content %}

<div class="row justify-content-center">
    <ul class="nav nav-tabs">
        <div class="col text-center"><li class="nav-item">
            <a id="nav_home" class="nav-link" href="{{ url_for('main.home') }}">
                Home
            </a>
        </li></div>
        <div class="col text-center"><li class="nav-item">
            <a id="nav_rules" class="nav-link" href="{{ url_for('main.rules') }}">
                Rules
            </a>
        </li></div>
        <div class="col text-center"><li class="nav-item">
            <a id="nav_graphql" class="nav-link" href="{{ url_for('graphql') }}">
                API
            </a>
        </li></div>
        <div class="col text-center"><li class="nav-item">
            <a id="nav_feedback" class="nav-link" href="{{ url_for('main.feedback') }}">
                Feedback
            </a>
        </li></div>
        <div class="col text-center"><li class="nav-item">
            <a id="nav_profile" class="nav-link" href="{{ url_for('user.edit_user_profile') }}">
                Profile
            </a>
        </li></div>
        <div class="col text-center"><li class="nav-item">
            {% if call_or_get(current_user.is_authenticated) %}
                <a id="nav_logout" class="nav-link" href="{{ url_for('user.logout') }}">
                    Logout
                </a>
            {% else %}
                <a id="nav_login" class="nav-link" href="{{ url_for('user.login') }}">
                    Login
                </a>
            {% endif %}
        </li></div>
    </ul>
</div>

{% block settings_navs_content %}
{% endblock %}

{% endblock %}